### ISSUE TITLE
System Testing and Validation

### ISSUE THREAD

**Issue by David-Shang** [bellabaohaha/CITS5206-Gp2#40] opened 2024-08-22 06:45 UTC
Conduct end-to-end testing of the system, validate data transmission, and refine any issues found.

**Comment by dharaninagala** [comment] 2024-10-18 05:52
The following are the detailed steps for end to end testing performed : 

**Overview**
The soil moisture monitoring system was tested on October 4th, 2024, between 3:30 PM and 4:00 PM at James Oval, University of Western Australia (UWA). The goal of the test was to assess the performance of the LoRa-based system in transmitting soil moisture data from three sensors embedded at different depths in the soil and monitor power consumption.

**Test Setup**
Moisture Sensors: Three sensors were placed at depths of 10 cm, 20 cm, and 30 cm to capture soil moisture content.

 **Test Procedure**
Initially, the sender and receiver were placed approximately 1 km apart, but no transmission data was received. It is likely that the buildings and the surrounding topology caused signal interference. To resolve this, the receiver was moved closer, with the sender placed on one side of the ground and the receiver on the opposite side. This adjustment allowed for successful transmission and data reception.

**Battery Monitoring**
During the test, the battery was monitored by unplugging the system to track battery drainage. The battery typically drained by 1% every 15 minutes, demonstrating efficient power consumption throughout the testing period.
The first transmission packet was missed, as seen from the test data. Data was successfully transmitted after the adjustment in receiver positioning, with consistent signal strength and data integrity observed in subsequent packets. The testing results table can be viewed in the following link https://github.com/bellabaohaha/CITS5206-Gp2/blob/main/Deliverables/Testing_Readings.xlsx

**Transmission Results**

The first transmission packet was missed, as seen from the test data. Data was successfully transmitted after the adjustment in receiver positioning, with consistent signal strength and data integrity observed in subsequent packets. 

Once the data packets are received by the master gateway (receiver), additional information such as the gateway's position details (latitude and longitude), along with the signal strength indicators (RSSI and SNR) and packet size, are appended to the data. This enriched data is then transmitted to AWS IoT Core. Upon reaching the cloud platform, the data is stored in AWS DynamoDB for secure and scalable storage. The dashboard retrieves the data from DynamoDB and displays it on the screen, providing real-time insights and visualizations based on the collected information.

The soil moisture monitoring system successfully transmitted data over a shorter distance after resolving the initial transmission issue caused by the environment's topology. The system's energy efficiency was confirmed by minimal battery drain during the test, and soil moisture readings were consistent across all sensor depths. Future tests may include exploring different LoRa configurations or alternate locations to minimize packet loss over longer distances.

**Closed as completed by dharaninagala** 2024-10-18 05:52 UTC
